services:
  postgres:
    container_name: postgres_real_time_chat_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: real_time_chat_db
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - real_time_chat_network
    restart: unless-stopped
  keycloak:
    container_name: keycloak_real_time_chat_container
    image: quay.io/keycloak/keycloak:26.0.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: real_time_chat_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - real_time_chat_network
    restart: unless-stopped
    command: start-dev

networks:
  real_time_chat_network:
    driver: bridge

volumes:
  postgres_data:
