/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChatResponse {
  id?: string;
  isRecieverOnline?: boolean;
  lastMessageContent?: string;
  lastMessageTime?: string;
  name?: string;
  recieverId?: string;
  senderId?: string;
  unreadMessagesCount?: number;
}
