/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { findAllUsersExceptSelf } from '../fn/user/find-all-users-except-self';
import { FindAllUsersExceptSelf$Params } from '../fn/user/find-all-users-except-self';
import { UserResponse } from '../models/user-response';


/**
 * A controller for managing users
 */
@Injectable({ providedIn: 'root' })
export class UserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findAllUsersExceptSelf()` */
  static readonly FindAllUsersExceptSelfPath = '/api/v1/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllUsersExceptSelf()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllUsersExceptSelf$Response(params?: FindAllUsersExceptSelf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserResponse>>> {
    return findAllUsersExceptSelf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllUsersExceptSelf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllUsersExceptSelf(params?: FindAllUsersExceptSelf$Params, context?: HttpContext): Observable<Array<UserResponse>> {
    return this.findAllUsersExceptSelf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserResponse>>): Array<UserResponse> => r.body)
    );
  }

}
